[package]
name = "registry"
version = "0.1.0"
edition = "2024"

[dependencies]
proto = { path = "../../libs/proto" }
sha256 = { version = "1" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "process"] }
tokio-stream = { features = ["io-util"], version = "0" }
tonic = "0"
